In [3]:
import numpy as np

In [25]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

arr = np.array(list)

print(arr * 4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
minimum = np.argmin(arr)
maximum = np.argmax(arr)
print(arr[minimum])
print(arr[maximum])
print(np.min(arr))
print(np.max(arr))
greater_20 = arr[arr>20]
print(greater_20)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
4
50
4
50
[27 31 50 39 35]


In [108]:
def prime_mag(arr):
    rows_with_prime = []
    for row in arr:
        for number in row:
            factors = 0
            for i in range(number + 1):
                if number % (i + 1) == 0:
                    factors += 1
            if factors == 2:
                rows_with_prime.append(row.tolist())
                break
    print(rows_with_prime)

arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

prime_mag(arr)

[[2, 3, 5], [11, 13, 17], [7, 10, 13]]


In [15]:
def eight_by_eight():
    print(np.zeros((8, 8)))

def alternating_ones(arr):
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if (i + j) % 2 == 0:
                arr[i, j] = 1
    return arr
    
checkers = alternating_ones(np.zeros((8, 8)))
print(checkers)

finished_checkers = checkers.astype(int)
print(finished_checkers)

def reverse_the_board(arr):
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if arr[i, j] == 0:
                arr[i, j] == 1
            else: 
                arr[i, j] == 0
    return arr

reverse_checkers = reverse_the_board(finished_checkers)
print(reverse_checkers)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [15]:
def spacer(words, number):
    for word in words:
        i = 0
        while i < number:
            word = np.char.join(' ', word)
            i += 1
        print(word)

spacer(["galaxy", "cluster"], 4)

g               a               l               a               x               y
c               l               u               s               t               e               r


In [26]:
def second_brightest(stars):
    second_brightest_stars = []
    for row in stars:
        row = np.delete(row, np.argmax(row))
        second_brightest = int(np.max(row))
        second_brightest_stars.append(second_brightest)
    return second_brightest_stars
        

stars = np.random.randint(500, 2000, (5, 5))
second_brightest(stars)

[1578, 993, 1943, 967, 1413]